version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: gdo-postgres
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gdo_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gdo_db"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  postgres-data: